### PR TITLE
cycle-through-images solution

### PR DESCRIPTION
**Pull request by Ifycode**
PR contains the solution for cycling through images:
- Using intervals
- By clicking a button

### CODE REVIEW

**Comment by Ifycode** [comment]
Let me know if you have any issues or questions running the code.

**Comment by Danbaba1** [comment]
Okay ma will do.

**Comment by Danbaba1** [comment]
@Ifycode Excuse me ma how do I pull your changes or open them up in my vscode.

**Comment by Ifycode** [comment]
@Danbaba1 
Checkout to main branch:
`git checkout main`

Then use the pull command:
`git pull origin main`

**Comment by Danbaba1** [comment]
Thank you Adam

**Pull request merged**
